#!/usr/bin/env python2

import sys
import os
import pipes
import subprocess
from googlevoice import Voice

def file_get_contents(filename):
    with open(filename) as f:
        return f.read()

def main():
    if len(sys.argv) < 2:
        print("Usage: %s <command>" % sys.argv[0])
        sys.exit(1)

    who = file_get_contents(os.path.expanduser("~/.dingwho")).strip()
    what = sys.argv[1]
    command = ' '.join(map(pipes.quote, sys.argv[1:]))
    result = subprocess.call(command, shell=True)

    message = "[%s] %s" % (result, command)
    if len(message) > 160:
        message = message[0:157] + '...'

    voice = Voice()
    voice.login()
    voice.send_sms(who, message)

if __name__ == '__main__':
    main()
